// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCMO1ZfElSvfyrSruZELK98Jypb-yY9qM0',
    appId: '1:1087778694235:web:d96b657005e4e6dcf30b7e',
    messagingSenderId: '1087778694235',
    projectId: 'flutterwithfirebaseow',
    authDomain: 'flutterwithfirebaseow.firebaseapp.com',
    storageBucket: 'flutterwithfirebaseow.appspot.com',
    measurementId: 'G-4LQYS3XQXZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCk_QegU6jAQpMVZAO92OgTrhZe80w3ToM',
    appId: '1:1087778694235:android:dd5cdf8b2b03d65bf30b7e',
    messagingSenderId: '1087778694235',
    projectId: 'flutterwithfirebaseow',
    storageBucket: 'flutterwithfirebaseow.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDACRPMuTltiuG_nNlN9YADAWuIKSSqHls',
    appId: '1:1087778694235:ios:29821976bc56e6ddf30b7e',
    messagingSenderId: '1087778694235',
    projectId: 'flutterwithfirebaseow',
    storageBucket: 'flutterwithfirebaseow.appspot.com',
    androidClientId: '1087778694235-delcjq7smo0ki2hor3pfqbf73fmrltjf.apps.googleusercontent.com',
    iosClientId: '1087778694235-c81tb6nps4km7bmbufhq5cnb8ivattdm.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterWithFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDACRPMuTltiuG_nNlN9YADAWuIKSSqHls',
    appId: '1:1087778694235:ios:29821976bc56e6ddf30b7e',
    messagingSenderId: '1087778694235',
    projectId: 'flutterwithfirebaseow',
    storageBucket: 'flutterwithfirebaseow.appspot.com',
    androidClientId: '1087778694235-delcjq7smo0ki2hor3pfqbf73fmrltjf.apps.googleusercontent.com',
    iosClientId: '1087778694235-c81tb6nps4km7bmbufhq5cnb8ivattdm.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterWithFirebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCMO1ZfElSvfyrSruZELK98Jypb-yY9qM0',
    appId: '1:1087778694235:web:2aed041da43b18a7f30b7e',
    messagingSenderId: '1087778694235',
    projectId: 'flutterwithfirebaseow',
    authDomain: 'flutterwithfirebaseow.firebaseapp.com',
    storageBucket: 'flutterwithfirebaseow.appspot.com',
    measurementId: 'G-NR6V2CTEQ8',
  );

}